language: ruby
rvm: 2.3.1
env: RAILS_ENV=test
script:
  - bundle exec rspec
addons:
  postgresql: "9.4"
  firefox: "61.0.2"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate

  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install: bundle install --jobs=3 --retry=3
